"""
Section 6: Main Internal Algorithms
Three algorithms in this module are all deterministic, meaning that their 
output is completely determined by their input. No randomness is sampled inside 
of these algorithms. They will be used to construct ML-KEM.

They make use of the parameters 𝑛, 𝑞, 𝑘, 𝑑𝑢, and 𝑑𝑣. 
The subroutines they invoke additionally make use of the parameters 𝜂1 and 𝜂2. 
While 𝑛 is always 256 and 𝑞 is always 3329, the remaining parameters vary among the 
possible parameter sets.

The interfaces specified in this module should not be made available to 
applications other than for testing purposes, and the random seeds shall be generated by 
the cryptographic module.
"""
import k_pke
import hash_functions

# ML-KEM-512 params
ETA1 = 3
ETA2 = 2

def keygen_internal(d, z, k, eta1):
    """
    Implements Algorithm 16: ML-KEM.KeyGen_internal(d, z)

    Parameters:
        d    : 32-byte randomness input
        z    : 32-byte randomness input
        k    : parameter set value (2, 3, or 4)
        eta1 : parameter set value

    Assumes the following functions already exist:
        - k_pke_keygen(d, k, eta1) -> (ek_pke, dk_pke)
        - H(s) -> 32-byte hash output

    Returns:
        (ek, dk)
          ek in B^(384k + 32)
          dk in B^(768k + 96)
    """
    d = bytes(d)
    z = bytes(z)

    if len(d) != 32:
        raise ValueError("d must be exactly 32 bytes.")
    if len(z) != 32:
        raise ValueError("z must be exactly 32 bytes.")

    ek_pke, dk_pke = k_pke.k_pke_keygen(d, k=k, eta1=eta1)

    ek = ek_pke # KEM encaps key is just the PKE encryption key
    dk = dk_pke + ek + hash_functions.H(ek) + z # KEM decaps key includes PKE decryption key

    return ek, dk

def encaps_internal(ek, m, k, eta1, eta2, du, dv):
    """
    Implements Algorithm 17: ML-KEM.Encaps_internal(ek, m)

    Parameters:
        ek   : encapsulation key, length 384*k + 32 bytes
        m    : 32-byte randomness input
        k    : parameter set value
        eta1 : parameter for K-PKE.Encrypt
        eta2 : parameter for K-PKE.Encrypt
        du   : compression parameter
        dv   : compression parameter

    Returns:
        (K, c)
          K : 32-byte shared secret key
          c : ciphertext
    """
    ek = bytes(ek)
    m = bytes(m)

    if len(m) != 32:
        raise ValueError("m must be exactly 32 bytes.")
    if len(ek) != 384 * k + 32:
        raise ValueError(f"ek must have length {384 * k + 32} bytes.")

    K, r = hash_functions.G(m + hash_functions.H(ek)) # derive shared secret key K and randomness r
    c = k_pke.k_pke_encrypt(ek, m, r, k=k, eta1=eta1, eta2=eta2, du=du, dv=dv) # encrypt 𝑚 using K-PKE with randomness 𝑟

    return K, c

def decaps_internal(dk, c, k, du, dv):
    """
    Implements Algorithm 18: ML-KEM.Decaps_internal(dk, c)

    Parameters:
        dk : decapsulation key, length 768*k + 96 bytes
        c  : ciphertext, length 32 * (du*k + dv) bytes
        k  : parameter set value
        du : compression parameter
        dv : compression parameter

    Also assumes eta1 and eta2 are available as globals or constants
    for the chosen ML-KEM parameter set.
    """
    dk = bytes(dk)
    c = bytes(c)

    expected_dk_len = 768 * k + 96
    expected_c_len = 32 * (du * k + dv)

    if len(dk) != expected_dk_len:
        raise ValueError(f"dk must have length {expected_dk_len} bytes.")
    if len(c) != expected_c_len:
        raise ValueError(f"c must have length {expected_c_len} bytes.")

    # 1-4: parse decapsulation key
    dk_pke = dk[:384 * k]
    ek_pke = dk[384 * k:768 * k + 32]
    h = dk[768 * k + 32:768 * k + 64]
    z = dk[768 * k + 64:768 * k + 96]

    # 5: decrypt ciphertext
    m_prime = k_pke.k_pke_decrypt(dk_pke, c, k=k, du=du, dv=dv)

    # 6: derive candidate shared key and encryption randomness
    K_prime, r_prime = hash_functions.G(m_prime + h)

    # 7: implicit rejection value
    K_bar = hash_functions.J(z + c)

    # 8: re-encrypt
    c_prime = k_pke.k_pke_encrypt(
        ek_pke,
        m_prime,
        r_prime,
        k=k,
        eta1=ETA1,
        eta2=ETA2,
        du=du,
        dv=dv,
    )

    # 9-11: compare ciphertexts
    if c != c_prime:
        K_prime = K_bar

    # 12: return shared secret
    return K_prime

def main():
    # d = bytes(range(32))
    # z = bytes(range(32, 64))

    # # ML-KEM-512-style parameters
    # ek, dk = keygen_internal(d, z, k=2, eta1=3)

    # print(len(ek))   # 384*2 + 32 = 800
    # print(len(dk))   # 768*2 + 96 = 1632
    # print(ek[:16].hex())
    # print(dk[:16].hex())

    d = bytes(range(32))
    z = bytes(range(32, 64))

    # Example: ML-KEM-512 parameters
    k = 2
    du = 10
    dv = 4

    d = bytes(range(32))
    z = bytes(range(32, 64))
    m = bytes([7] * 32)

    ek, dk = keygen_internal(d, z, k=k, eta1=ETA1)
    K1, c = encaps_internal(ek, m, k=k, eta1=ETA1, eta2=ETA2, du=du, dv=dv)
    K2 = decaps_internal(dk, c, k=k, du=du, dv=dv)
    print(K1 == K2)
    
if __name__ == "__main__":
    main()